/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.records


import io.github.novemdecillion.adapter.jooq.tables.CurrentGroupTransitionTable
import io.github.novemdecillion.adapter.jooq.tables.interfaces.ICurrentGroupTransition

import java.util.UUID

import org.jooq.Field
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CurrentGroupTransitionRecord() : TableRecordImpl<CurrentGroupTransitionRecord>(CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION), Record8<UUID?, UUID?, UUID?, String?, UUID?, Int?, String?, String?>, ICurrentGroupTransition {

    override var groupTransitionId: UUID?
        set(value) = set(0, value)
        get() = get(0) as UUID?

    override var groupGenerationId: UUID?
        set(value) = set(1, value)
        get() = get(1) as UUID?

    override var groupOriginId: UUID?
        set(value) = set(2, value)
        get() = get(2) as UUID?

    override var groupName: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    override var parentGroupTransitionId: UUID?
        set(value) = set(4, value)
        get() = get(4) as UUID?

    override var layer: Int?
        set(value) = set(5, value)
        get() = get(5) as Int?

    override var path: String?
        set(value) = set(6, value)
        get() = get(6) as String?

    override var pathName: String?
        set(value) = set(7, value)
        get() = get(7) as String?

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<UUID?, UUID?, UUID?, String?, UUID?, Int?, String?, String?> = super.fieldsRow() as Row8<UUID?, UUID?, UUID?, String?, UUID?, Int?, String?, String?>
    override fun valuesRow(): Row8<UUID?, UUID?, UUID?, String?, UUID?, Int?, String?, String?> = super.valuesRow() as Row8<UUID?, UUID?, UUID?, String?, UUID?, Int?, String?, String?>
    override fun field1(): Field<UUID?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_TRANSITION_ID
    override fun field2(): Field<UUID?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_GENERATION_ID
    override fun field3(): Field<UUID?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_ORIGIN_ID
    override fun field4(): Field<String?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_NAME
    override fun field5(): Field<UUID?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.PARENT_GROUP_TRANSITION_ID
    override fun field6(): Field<Int?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.LAYER
    override fun field7(): Field<String?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.PATH
    override fun field8(): Field<String?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.PATH_NAME
    override fun component1(): UUID? = groupTransitionId
    override fun component2(): UUID? = groupGenerationId
    override fun component3(): UUID? = groupOriginId
    override fun component4(): String? = groupName
    override fun component5(): UUID? = parentGroupTransitionId
    override fun component6(): Int? = layer
    override fun component7(): String? = path
    override fun component8(): String? = pathName
    override fun value1(): UUID? = groupTransitionId
    override fun value2(): UUID? = groupGenerationId
    override fun value3(): UUID? = groupOriginId
    override fun value4(): String? = groupName
    override fun value5(): UUID? = parentGroupTransitionId
    override fun value6(): Int? = layer
    override fun value7(): String? = path
    override fun value8(): String? = pathName

    override fun value1(value: UUID?): CurrentGroupTransitionRecord {
        this.groupTransitionId = value
        return this
    }

    override fun value2(value: UUID?): CurrentGroupTransitionRecord {
        this.groupGenerationId = value
        return this
    }

    override fun value3(value: UUID?): CurrentGroupTransitionRecord {
        this.groupOriginId = value
        return this
    }

    override fun value4(value: String?): CurrentGroupTransitionRecord {
        this.groupName = value
        return this
    }

    override fun value5(value: UUID?): CurrentGroupTransitionRecord {
        this.parentGroupTransitionId = value
        return this
    }

    override fun value6(value: Int?): CurrentGroupTransitionRecord {
        this.layer = value
        return this
    }

    override fun value7(value: String?): CurrentGroupTransitionRecord {
        this.path = value
        return this
    }

    override fun value8(value: String?): CurrentGroupTransitionRecord {
        this.pathName = value
        return this
    }

    override fun values(value1: UUID?, value2: UUID?, value3: UUID?, value4: String?, value5: UUID?, value6: Int?, value7: String?, value8: String?): CurrentGroupTransitionRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ICurrentGroupTransition) {
        groupTransitionId = from.groupTransitionId
        groupGenerationId = from.groupGenerationId
        groupOriginId = from.groupOriginId
        groupName = from.groupName
        parentGroupTransitionId = from.parentGroupTransitionId
        layer = from.layer
        path = from.path
        pathName = from.pathName
    }

    override fun <E : ICurrentGroupTransition> into(into: E): E {
        into.from(this)
        return into
    }

    /**
     * Create a detached, initialised CurrentGroupTransitionRecord
     */
    constructor(groupTransitionId: UUID? = null, groupGenerationId: UUID? = null, groupOriginId: UUID? = null, groupName: String? = null, parentGroupTransitionId: UUID? = null, layer: Int? = null, path: String? = null, pathName: String? = null): this() {
        this.groupTransitionId = groupTransitionId
        this.groupGenerationId = groupGenerationId
        this.groupOriginId = groupOriginId
        this.groupName = groupName
        this.parentGroupTransitionId = parentGroupTransitionId
        this.layer = layer
        this.path = path
        this.pathName = pathName
    }
}
