/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.records


import io.github.novemdecillion.adapter.jooq.tables.CurrentGroupTransitionTable
import io.github.novemdecillion.adapter.jooq.tables.interfaces.ICurrentGroupTransition

import java.util.UUID

import org.jooq.Field
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CurrentGroupTransitionRecord() : TableRecordImpl<CurrentGroupTransitionRecord>(CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION), Record4<UUID?, UUID?, UUID?, String?>, ICurrentGroupTransition {

    override var groupTransitionId: UUID?
        set(value) = set(0, value)
        get() = get(0) as UUID?

    override var groupGenerationId: UUID?
        set(value) = set(1, value)
        get() = get(1) as UUID?

    override var groupOriginId: UUID?
        set(value) = set(2, value)
        get() = get(2) as UUID?

    override var groupName: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<UUID?, UUID?, UUID?, String?> = super.fieldsRow() as Row4<UUID?, UUID?, UUID?, String?>
    override fun valuesRow(): Row4<UUID?, UUID?, UUID?, String?> = super.valuesRow() as Row4<UUID?, UUID?, UUID?, String?>
    override fun field1(): Field<UUID?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_TRANSITION_ID
    override fun field2(): Field<UUID?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_GENERATION_ID
    override fun field3(): Field<UUID?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_ORIGIN_ID
    override fun field4(): Field<String?> = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION.GROUP_NAME
    override fun component1(): UUID? = groupTransitionId
    override fun component2(): UUID? = groupGenerationId
    override fun component3(): UUID? = groupOriginId
    override fun component4(): String? = groupName
    override fun value1(): UUID? = groupTransitionId
    override fun value2(): UUID? = groupGenerationId
    override fun value3(): UUID? = groupOriginId
    override fun value4(): String? = groupName

    override fun value1(value: UUID?): CurrentGroupTransitionRecord {
        this.groupTransitionId = value
        return this
    }

    override fun value2(value: UUID?): CurrentGroupTransitionRecord {
        this.groupGenerationId = value
        return this
    }

    override fun value3(value: UUID?): CurrentGroupTransitionRecord {
        this.groupOriginId = value
        return this
    }

    override fun value4(value: String?): CurrentGroupTransitionRecord {
        this.groupName = value
        return this
    }

    override fun values(value1: UUID?, value2: UUID?, value3: UUID?, value4: String?): CurrentGroupTransitionRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ICurrentGroupTransition) {
        groupTransitionId = from.groupTransitionId
        groupGenerationId = from.groupGenerationId
        groupOriginId = from.groupOriginId
        groupName = from.groupName
    }

    override fun <E : ICurrentGroupTransition> into(into: E): E {
        into.from(this)
        return into
    }

    /**
     * Create a detached, initialised CurrentGroupTransitionRecord
     */
    constructor(groupTransitionId: UUID? = null, groupGenerationId: UUID? = null, groupOriginId: UUID? = null, groupName: String? = null): this() {
        this.groupTransitionId = groupTransitionId
        this.groupGenerationId = groupGenerationId
        this.groupOriginId = groupOriginId
        this.groupName = groupName
    }
}
