/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.records


import io.github.novemdecillion.adapter.jooq.tables.GroupTransitionTable
import io.github.novemdecillion.adapter.jooq.tables.interfaces.IGroupTransition

import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GroupTransitionRecord() : UpdatableRecordImpl<GroupTransitionRecord>(GroupTransitionTable.GROUP_TRANSITION), Record5<UUID?, UUID?, UUID?, String?, UUID?>, IGroupTransition {

    override var groupTransitionId: UUID?
        set(value) = set(0, value)
        get() = get(0) as UUID?

    override var groupGenerationId: UUID?
        set(value) = set(1, value)
        get() = get(1) as UUID?

    override var groupOriginId: UUID?
        set(value) = set(2, value)
        get() = get(2) as UUID?

    override var groupName: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    override var parentGroupTransitionId: UUID?
        set(value) = set(4, value)
        get() = get(4) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<UUID?, UUID?, UUID?, String?, UUID?> = super.fieldsRow() as Row5<UUID?, UUID?, UUID?, String?, UUID?>
    override fun valuesRow(): Row5<UUID?, UUID?, UUID?, String?, UUID?> = super.valuesRow() as Row5<UUID?, UUID?, UUID?, String?, UUID?>
    override fun field1(): Field<UUID?> = GroupTransitionTable.GROUP_TRANSITION.GROUP_TRANSITION_ID
    override fun field2(): Field<UUID?> = GroupTransitionTable.GROUP_TRANSITION.GROUP_GENERATION_ID
    override fun field3(): Field<UUID?> = GroupTransitionTable.GROUP_TRANSITION.GROUP_ORIGIN_ID
    override fun field4(): Field<String?> = GroupTransitionTable.GROUP_TRANSITION.GROUP_NAME
    override fun field5(): Field<UUID?> = GroupTransitionTable.GROUP_TRANSITION.PARENT_GROUP_TRANSITION_ID
    override fun component1(): UUID? = groupTransitionId
    override fun component2(): UUID? = groupGenerationId
    override fun component3(): UUID? = groupOriginId
    override fun component4(): String? = groupName
    override fun component5(): UUID? = parentGroupTransitionId
    override fun value1(): UUID? = groupTransitionId
    override fun value2(): UUID? = groupGenerationId
    override fun value3(): UUID? = groupOriginId
    override fun value4(): String? = groupName
    override fun value5(): UUID? = parentGroupTransitionId

    override fun value1(value: UUID?): GroupTransitionRecord {
        this.groupTransitionId = value
        return this
    }

    override fun value2(value: UUID?): GroupTransitionRecord {
        this.groupGenerationId = value
        return this
    }

    override fun value3(value: UUID?): GroupTransitionRecord {
        this.groupOriginId = value
        return this
    }

    override fun value4(value: String?): GroupTransitionRecord {
        this.groupName = value
        return this
    }

    override fun value5(value: UUID?): GroupTransitionRecord {
        this.parentGroupTransitionId = value
        return this
    }

    override fun values(value1: UUID?, value2: UUID?, value3: UUID?, value4: String?, value5: UUID?): GroupTransitionRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IGroupTransition) {
        groupTransitionId = from.groupTransitionId
        groupGenerationId = from.groupGenerationId
        groupOriginId = from.groupOriginId
        groupName = from.groupName
        parentGroupTransitionId = from.parentGroupTransitionId
    }

    override fun <E : IGroupTransition> into(into: E): E {
        into.from(this)
        return into
    }

    /**
     * Create a detached, initialised GroupTransitionRecord
     */
    constructor(groupTransitionId: UUID? = null, groupGenerationId: UUID? = null, groupOriginId: UUID? = null, groupName: String? = null, parentGroupTransitionId: UUID? = null): this() {
        this.groupTransitionId = groupTransitionId
        this.groupGenerationId = groupGenerationId
        this.groupOriginId = groupOriginId
        this.groupName = groupName
        this.parentGroupTransitionId = parentGroupTransitionId
    }
}
