/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.records


import io.github.novemdecillion.adapter.jooq.tables.GroupGenerationTable
import io.github.novemdecillion.adapter.jooq.tables.interfaces.IGroupGeneration

import java.time.LocalDate
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GroupGenerationRecord() : UpdatableRecordImpl<GroupGenerationRecord>(GroupGenerationTable.GROUP_GENERATION), Record2<UUID?, LocalDate?>, IGroupGeneration {

    override var groupGenerationId: UUID?
        set(value) = set(0, value)
        get() = get(0) as UUID?

    override var startDate: LocalDate?
        set(value) = set(1, value)
        get() = get(1) as LocalDate?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<UUID?, LocalDate?> = super.fieldsRow() as Row2<UUID?, LocalDate?>
    override fun valuesRow(): Row2<UUID?, LocalDate?> = super.valuesRow() as Row2<UUID?, LocalDate?>
    override fun field1(): Field<UUID?> = GroupGenerationTable.GROUP_GENERATION.GROUP_GENERATION_ID
    override fun field2(): Field<LocalDate?> = GroupGenerationTable.GROUP_GENERATION.START_DATE
    override fun component1(): UUID? = groupGenerationId
    override fun component2(): LocalDate? = startDate
    override fun value1(): UUID? = groupGenerationId
    override fun value2(): LocalDate? = startDate

    override fun value1(value: UUID?): GroupGenerationRecord {
        this.groupGenerationId = value
        return this
    }

    override fun value2(value: LocalDate?): GroupGenerationRecord {
        this.startDate = value
        return this
    }

    override fun values(value1: UUID?, value2: LocalDate?): GroupGenerationRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IGroupGeneration) {
        groupGenerationId = from.groupGenerationId
        startDate = from.startDate
    }

    override fun <E : IGroupGeneration> into(into: E): E {
        into.from(this)
        return into
    }

    /**
     * Create a detached, initialised GroupGenerationRecord
     */
    constructor(groupGenerationId: UUID? = null, startDate: LocalDate? = null): this() {
        this.groupGenerationId = groupGenerationId
        this.startDate = startDate
    }
}
