/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.records


import io.github.novemdecillion.adapter.jooq.tables.StudyTable
import io.github.novemdecillion.adapter.jooq.tables.interfaces.IStudy

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class StudyRecord() : UpdatableRecordImpl<StudyRecord>(StudyTable.STUDY), Record9<UUID?, UUID?, String?, String?, Int?, String?, Int?, OffsetDateTime?, OffsetDateTime?>, IStudy {

    override var studyId: UUID?
        set(value) = set(0, value)
        get() = get(0) as UUID?

    override var accountId: UUID?
        set(value) = set(1, value)
        get() = get(1) as UUID?

    override var slideId: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    override var progress: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    override var progressRate: Int?
        set(value) = set(4, value)
        get() = get(4) as Int?

    override var answer: String?
        set(value) = set(5, value)
        get() = get(5) as String?

    override var score: Int?
        set(value) = set(6, value)
        get() = get(6) as Int?

    override var startAt: OffsetDateTime?
        set(value) = set(7, value)
        get() = get(7) as OffsetDateTime?

    override var endAt: OffsetDateTime?
        set(value) = set(8, value)
        get() = get(8) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<UUID?, UUID?, String?, String?, Int?, String?, Int?, OffsetDateTime?, OffsetDateTime?> = super.fieldsRow() as Row9<UUID?, UUID?, String?, String?, Int?, String?, Int?, OffsetDateTime?, OffsetDateTime?>
    override fun valuesRow(): Row9<UUID?, UUID?, String?, String?, Int?, String?, Int?, OffsetDateTime?, OffsetDateTime?> = super.valuesRow() as Row9<UUID?, UUID?, String?, String?, Int?, String?, Int?, OffsetDateTime?, OffsetDateTime?>
    override fun field1(): Field<UUID?> = StudyTable.STUDY.STUDY_ID
    override fun field2(): Field<UUID?> = StudyTable.STUDY.ACCOUNT_ID
    override fun field3(): Field<String?> = StudyTable.STUDY.SLIDE_ID
    override fun field4(): Field<String?> = StudyTable.STUDY.PROGRESS
    override fun field5(): Field<Int?> = StudyTable.STUDY.PROGRESS_RATE
    override fun field6(): Field<String?> = StudyTable.STUDY.ANSWER
    override fun field7(): Field<Int?> = StudyTable.STUDY.SCORE
    override fun field8(): Field<OffsetDateTime?> = StudyTable.STUDY.START_AT
    override fun field9(): Field<OffsetDateTime?> = StudyTable.STUDY.END_AT
    override fun component1(): UUID? = studyId
    override fun component2(): UUID? = accountId
    override fun component3(): String? = slideId
    override fun component4(): String? = progress
    override fun component5(): Int? = progressRate
    override fun component6(): String? = answer
    override fun component7(): Int? = score
    override fun component8(): OffsetDateTime? = startAt
    override fun component9(): OffsetDateTime? = endAt
    override fun value1(): UUID? = studyId
    override fun value2(): UUID? = accountId
    override fun value3(): String? = slideId
    override fun value4(): String? = progress
    override fun value5(): Int? = progressRate
    override fun value6(): String? = answer
    override fun value7(): Int? = score
    override fun value8(): OffsetDateTime? = startAt
    override fun value9(): OffsetDateTime? = endAt

    override fun value1(value: UUID?): StudyRecord {
        this.studyId = value
        return this
    }

    override fun value2(value: UUID?): StudyRecord {
        this.accountId = value
        return this
    }

    override fun value3(value: String?): StudyRecord {
        this.slideId = value
        return this
    }

    override fun value4(value: String?): StudyRecord {
        this.progress = value
        return this
    }

    override fun value5(value: Int?): StudyRecord {
        this.progressRate = value
        return this
    }

    override fun value6(value: String?): StudyRecord {
        this.answer = value
        return this
    }

    override fun value7(value: Int?): StudyRecord {
        this.score = value
        return this
    }

    override fun value8(value: OffsetDateTime?): StudyRecord {
        this.startAt = value
        return this
    }

    override fun value9(value: OffsetDateTime?): StudyRecord {
        this.endAt = value
        return this
    }

    override fun values(value1: UUID?, value2: UUID?, value3: String?, value4: String?, value5: Int?, value6: String?, value7: Int?, value8: OffsetDateTime?, value9: OffsetDateTime?): StudyRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IStudy) {
        studyId = from.studyId
        accountId = from.accountId
        slideId = from.slideId
        progress = from.progress
        progressRate = from.progressRate
        answer = from.answer
        score = from.score
        startAt = from.startAt
        endAt = from.endAt
    }

    override fun <E : IStudy> into(into: E): E {
        into.from(this)
        return into
    }

    /**
     * Create a detached, initialised StudyRecord
     */
    constructor(studyId: UUID? = null, accountId: UUID? = null, slideId: String? = null, progress: String? = null, progressRate: Int? = null, answer: String? = null, score: Int? = null, startAt: OffsetDateTime? = null, endAt: OffsetDateTime? = null): this() {
        this.studyId = studyId
        this.accountId = accountId
        this.slideId = slideId
        this.progress = progress
        this.progressRate = progressRate
        this.answer = answer
        this.score = score
        this.startAt = startAt
        this.endAt = endAt
    }
}
