/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.records


import io.github.novemdecillion.adapter.jooq.tables.UserAggregateTable
import io.github.novemdecillion.adapter.jooq.tables.interfaces.IUserAggregate
import io.github.novemdecillion.domain.Role

import java.util.UUID

import org.jooq.Field
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserAggregateRecord() : TableRecordImpl<UserAggregateRecord>(UserAggregateTable.USER_AGGREGATE), Record10<UUID?, String?, String?, String?, String?, String?, String?, Boolean?, UUID?, Role?>, IUserAggregate {

    override var accountId: UUID?
        set(value) = set(0, value)
        get() = get(0) as UUID?

    override var accountName: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    override var password: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    override var userName: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    override var email: String?
        set(value) = set(4, value)
        get() = get(4) as String?

    override var locale: String?
        set(value) = set(5, value)
        get() = get(5) as String?

    override var realmId: String?
        set(value) = set(6, value)
        get() = get(6) as String?

    override var enabled: Boolean?
        set(value) = set(7, value)
        get() = get(7) as Boolean?

    override var groupOriginId: UUID?
        set(value) = set(8, value)
        get() = get(8) as UUID?

    override var role: Role?
        set(value) = set(9, value)
        get() = get(9) as Role?

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<UUID?, String?, String?, String?, String?, String?, String?, Boolean?, UUID?, Role?> = super.fieldsRow() as Row10<UUID?, String?, String?, String?, String?, String?, String?, Boolean?, UUID?, Role?>
    override fun valuesRow(): Row10<UUID?, String?, String?, String?, String?, String?, String?, Boolean?, UUID?, Role?> = super.valuesRow() as Row10<UUID?, String?, String?, String?, String?, String?, String?, Boolean?, UUID?, Role?>
    override fun field1(): Field<UUID?> = UserAggregateTable.USER_AGGREGATE.ACCOUNT_ID
    override fun field2(): Field<String?> = UserAggregateTable.USER_AGGREGATE.ACCOUNT_NAME
    override fun field3(): Field<String?> = UserAggregateTable.USER_AGGREGATE.PASSWORD
    override fun field4(): Field<String?> = UserAggregateTable.USER_AGGREGATE.USER_NAME
    override fun field5(): Field<String?> = UserAggregateTable.USER_AGGREGATE.EMAIL
    override fun field6(): Field<String?> = UserAggregateTable.USER_AGGREGATE.LOCALE
    override fun field7(): Field<String?> = UserAggregateTable.USER_AGGREGATE.REALM_ID
    override fun field8(): Field<Boolean?> = UserAggregateTable.USER_AGGREGATE.ENABLED
    override fun field9(): Field<UUID?> = UserAggregateTable.USER_AGGREGATE.GROUP_ORIGIN_ID
    override fun field10(): Field<Role?> = UserAggregateTable.USER_AGGREGATE.ROLE
    override fun component1(): UUID? = accountId
    override fun component2(): String? = accountName
    override fun component3(): String? = password
    override fun component4(): String? = userName
    override fun component5(): String? = email
    override fun component6(): String? = locale
    override fun component7(): String? = realmId
    override fun component8(): Boolean? = enabled
    override fun component9(): UUID? = groupOriginId
    override fun component10(): Role? = role
    override fun value1(): UUID? = accountId
    override fun value2(): String? = accountName
    override fun value3(): String? = password
    override fun value4(): String? = userName
    override fun value5(): String? = email
    override fun value6(): String? = locale
    override fun value7(): String? = realmId
    override fun value8(): Boolean? = enabled
    override fun value9(): UUID? = groupOriginId
    override fun value10(): Role? = role

    override fun value1(value: UUID?): UserAggregateRecord {
        this.accountId = value
        return this
    }

    override fun value2(value: String?): UserAggregateRecord {
        this.accountName = value
        return this
    }

    override fun value3(value: String?): UserAggregateRecord {
        this.password = value
        return this
    }

    override fun value4(value: String?): UserAggregateRecord {
        this.userName = value
        return this
    }

    override fun value5(value: String?): UserAggregateRecord {
        this.email = value
        return this
    }

    override fun value6(value: String?): UserAggregateRecord {
        this.locale = value
        return this
    }

    override fun value7(value: String?): UserAggregateRecord {
        this.realmId = value
        return this
    }

    override fun value8(value: Boolean?): UserAggregateRecord {
        this.enabled = value
        return this
    }

    override fun value9(value: UUID?): UserAggregateRecord {
        this.groupOriginId = value
        return this
    }

    override fun value10(value: Role?): UserAggregateRecord {
        this.role = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: String?, value8: Boolean?, value9: UUID?, value10: Role?): UserAggregateRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IUserAggregate) {
        accountId = from.accountId
        accountName = from.accountName
        password = from.password
        userName = from.userName
        email = from.email
        locale = from.locale
        realmId = from.realmId
        enabled = from.enabled
        groupOriginId = from.groupOriginId
        role = from.role
    }

    override fun <E : IUserAggregate> into(into: E): E {
        into.from(this)
        return into
    }

    /**
     * Create a detached, initialised UserAggregateRecord
     */
    constructor(accountId: UUID? = null, accountName: String? = null, password: String? = null, userName: String? = null, email: String? = null, locale: String? = null, realmId: String? = null, enabled: Boolean? = null, groupOriginId: UUID? = null, role: Role? = null): this() {
        this.accountId = accountId
        this.accountName = accountName
        this.password = password
        this.userName = userName
        this.email = email
        this.locale = locale
        this.realmId = realmId
        this.enabled = enabled
        this.groupOriginId = groupOriginId
        this.role = role
    }
}
