/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables


import io.github.novemdecillion.adapter.jooq.DefaultSchema
import io.github.novemdecillion.adapter.jooq.keys.ACCOUNT_PKEY
import io.github.novemdecillion.adapter.jooq.keys.ACCOUNT_REALM_ACCOUNT_NAME_KEY
import io.github.novemdecillion.adapter.jooq.tables.records.AccountRecord

import java.util.UUID

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row10
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountTable(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AccountRecord>?,
    aliased: Table<AccountRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AccountRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>account</code>
         */
        val ACCOUNT = AccountTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AccountRecord> = AccountRecord::class.java

    /**
     * The column <code>account.account_id</code>.
     */
    val ACCOUNT_ID: TableField<AccountRecord, UUID?> = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>account.account_name</code>.
     */
    val ACCOUNT_NAME: TableField<AccountRecord, String?> = createField(DSL.name("account_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>account.password</code>.
     */
    val PASSWORD: TableField<AccountRecord, String?> = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>account.user_name</code>.
     */
    val USER_NAME: TableField<AccountRecord, String?> = createField(DSL.name("user_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>account.given_name</code>.
     */
    val GIVEN_NAME: TableField<AccountRecord, String?> = createField(DSL.name("given_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>account.family_name</code>.
     */
    val FAMILY_NAME: TableField<AccountRecord, String?> = createField(DSL.name("family_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>account.eastern</code>.
     */
    val EASTERN: TableField<AccountRecord, Boolean?> = createField(DSL.name("eastern"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>account.email</code>.
     */
    val EMAIL: TableField<AccountRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>account.realm</code>.
     */
    val REALM: TableField<AccountRecord, String?> = createField(DSL.name("realm"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>account.enabled</code>.
     */
    val ENABLED: TableField<AccountRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("true", SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<AccountRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AccountRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>account</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>account</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>account</code> table reference
     */
    constructor(): this(DSL.name("account"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AccountRecord>): this(Internal.createPathAlias(child, key), child, key, ACCOUNT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<AccountRecord> = ACCOUNT_PKEY
    override fun getKeys(): List<UniqueKey<AccountRecord>> = listOf(ACCOUNT_PKEY, ACCOUNT_REALM_ACCOUNT_NAME_KEY)
    override fun `as`(alias: String): AccountTable = AccountTable(DSL.name(alias), this)
    override fun `as`(alias: Name): AccountTable = AccountTable(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AccountTable = AccountTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AccountTable = AccountTable(name, null)

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row10<UUID?, String?, String?, String?, String?, String?, Boolean?, String?, String?, Boolean?> = super.fieldsRow() as Row10<UUID?, String?, String?, String?, String?, String?, Boolean?, String?, String?, Boolean?>
}
