/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables


import io.github.novemdecillion.adapter.jooq.DefaultSchema
import io.github.novemdecillion.adapter.jooq.keys.ACCOUNT_GROUP_AUTHORITY_0_PKEY
import io.github.novemdecillion.adapter.jooq.keys.ACCOUNT_GROUP_AUTHORITY_0__ACCOUNT_GROUP_AUTHORITY_ACCOUNT_ID_FKEY
import io.github.novemdecillion.adapter.jooq.tables.records.AccountGroupAuthority_0Record

import java.util.UUID

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountGroupAuthority_0Table(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AccountGroupAuthority_0Record>?,
    aliased: Table<AccountGroupAuthority_0Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<AccountGroupAuthority_0Record>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>account_group_authority_0</code>
         */
        val ACCOUNT_GROUP_AUTHORITY_0 = AccountGroupAuthority_0Table()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AccountGroupAuthority_0Record> = AccountGroupAuthority_0Record::class.java

    /**
     * The column <code>account_group_authority_0.account_id</code>.
     */
    val ACCOUNT_ID: TableField<AccountGroupAuthority_0Record, UUID?> = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>account_group_authority_0.group_transition_id</code>.
     */
    val GROUP_TRANSITION_ID: TableField<AccountGroupAuthority_0Record, UUID?> = createField(DSL.name("group_transition_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>account_group_authority_0.group_generation_id</code>.
     */
    val GROUP_GENERATION_ID: TableField<AccountGroupAuthority_0Record, Int?> = createField(DSL.name("group_generation_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>account_group_authority_0.role</code>.
     */
    val ROLE: TableField<AccountGroupAuthority_0Record, JSONB?> = createField(DSL.name("role"), SQLDataType.JSONB, this, "")

    private constructor(alias: Name, aliased: Table<AccountGroupAuthority_0Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AccountGroupAuthority_0Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>account_group_authority_0</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>account_group_authority_0</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>account_group_authority_0</code> table reference
     */
    constructor(): this(DSL.name("account_group_authority_0"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AccountGroupAuthority_0Record>): this(Internal.createPathAlias(child, key), child, key, ACCOUNT_GROUP_AUTHORITY_0, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<AccountGroupAuthority_0Record> = ACCOUNT_GROUP_AUTHORITY_0_PKEY
    override fun getKeys(): List<UniqueKey<AccountGroupAuthority_0Record>> = listOf(ACCOUNT_GROUP_AUTHORITY_0_PKEY)
    override fun getReferences(): List<ForeignKey<AccountGroupAuthority_0Record, *>> = listOf(ACCOUNT_GROUP_AUTHORITY_0__ACCOUNT_GROUP_AUTHORITY_ACCOUNT_ID_FKEY)

    private lateinit var _account: AccountTable
    fun account(): AccountTable {
        if (!this::_account.isInitialized)
            _account = AccountTable(this, ACCOUNT_GROUP_AUTHORITY_0__ACCOUNT_GROUP_AUTHORITY_ACCOUNT_ID_FKEY)

        return _account;
    }
    override fun `as`(alias: String): AccountGroupAuthority_0Table = AccountGroupAuthority_0Table(DSL.name(alias), this)
    override fun `as`(alias: Name): AccountGroupAuthority_0Table = AccountGroupAuthority_0Table(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AccountGroupAuthority_0Table = AccountGroupAuthority_0Table(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AccountGroupAuthority_0Table = AccountGroupAuthority_0Table(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<UUID?, UUID?, Int?, JSONB?> = super.fieldsRow() as Row4<UUID?, UUID?, Int?, JSONB?>
}
