/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables


import io.github.novemdecillion.adapter.jooq.DefaultSchema
import io.github.novemdecillion.adapter.jooq.keys.GROUP_ORIGIN_PKEY
import io.github.novemdecillion.adapter.jooq.tables.records.GroupOriginRecord

import java.util.UUID

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row1
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GroupOriginTable(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, GroupOriginRecord>?,
    aliased: Table<GroupOriginRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<GroupOriginRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>group_origin</code>
         */
        val GROUP_ORIGIN = GroupOriginTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GroupOriginRecord> = GroupOriginRecord::class.java

    /**
     * The column <code>group_origin.group_origin_id</code>.
     */
    val GROUP_ORIGIN_ID: TableField<GroupOriginRecord, UUID?> = createField(DSL.name("group_origin_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<GroupOriginRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<GroupOriginRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>group_origin</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>group_origin</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>group_origin</code> table reference
     */
    constructor(): this(DSL.name("group_origin"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, GroupOriginRecord>): this(Internal.createPathAlias(child, key), child, key, GROUP_ORIGIN, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<GroupOriginRecord> = GROUP_ORIGIN_PKEY
    override fun getKeys(): List<UniqueKey<GroupOriginRecord>> = listOf(GROUP_ORIGIN_PKEY)
    override fun `as`(alias: String): GroupOriginTable = GroupOriginTable(DSL.name(alias), this)
    override fun `as`(alias: Name): GroupOriginTable = GroupOriginTable(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): GroupOriginTable = GroupOriginTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): GroupOriginTable = GroupOriginTable(name, null)

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row1<UUID?> = super.fieldsRow() as Row1<UUID?>
}
