/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables


import io.github.novemdecillion.adapter.jooq.DefaultSchema
import io.github.novemdecillion.adapter.jooq.keys.GROUP_1_PKEY
import io.github.novemdecillion.adapter.jooq.keys.GROUP_1__GROUP_TRANSITION_GROUP_GENERATION_ID_FKEY
import io.github.novemdecillion.adapter.jooq.tables.records.Group_1Record

import java.util.UUID

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Group_1Table(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Group_1Record>?,
    aliased: Table<Group_1Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Group_1Record>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>group_1</code>
         */
        val GROUP_1 = Group_1Table()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Group_1Record> = Group_1Record::class.java

    /**
     * The column <code>group_1.group_transition_id</code>.
     */
    val GROUP_TRANSITION_ID: TableField<Group_1Record, UUID?> = createField(DSL.name("group_transition_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>group_1.group_generation_id</code>.
     */
    val GROUP_GENERATION_ID: TableField<Group_1Record, Int?> = createField(DSL.name("group_generation_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>group_1.group_name</code>.
     */
    val GROUP_NAME: TableField<Group_1Record, String?> = createField(DSL.name("group_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>group_1.parent_group_transition_id</code>.
     */
    val PARENT_GROUP_TRANSITION_ID: TableField<Group_1Record, UUID?> = createField(DSL.name("parent_group_transition_id"), SQLDataType.UUID, this, "")

    private constructor(alias: Name, aliased: Table<Group_1Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Group_1Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>group_1</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>group_1</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>group_1</code> table reference
     */
    constructor(): this(DSL.name("group_1"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Group_1Record>): this(Internal.createPathAlias(child, key), child, key, GROUP_1, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<Group_1Record> = GROUP_1_PKEY
    override fun getKeys(): List<UniqueKey<Group_1Record>> = listOf(GROUP_1_PKEY)
    override fun getReferences(): List<ForeignKey<Group_1Record, *>> = listOf(GROUP_1__GROUP_TRANSITION_GROUP_GENERATION_ID_FKEY)

    private lateinit var _groupGeneration: GroupGenerationTable
    fun groupGeneration(): GroupGenerationTable {
        if (!this::_groupGeneration.isInitialized)
            _groupGeneration = GroupGenerationTable(this, GROUP_1__GROUP_TRANSITION_GROUP_GENERATION_ID_FKEY)

        return _groupGeneration;
    }
    override fun `as`(alias: String): Group_1Table = Group_1Table(DSL.name(alias), this)
    override fun `as`(alias: Name): Group_1Table = Group_1Table(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Group_1Table = Group_1Table(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Group_1Table = Group_1Table(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<UUID?, Int?, String?, UUID?> = super.fieldsRow() as Row4<UUID?, Int?, String?, UUID?>
}
