#debug: true

app:
  slide:
    root-path: file:slides/

spring:
  application:
    name: e-learning
  cloud:
    gateway:
      routes:
        - uri: http://localhost:4200
          predicates:
            - Path=/**

  codec:
    max-in-memory-size: 10MB
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  security:
    oauth2:
      client:
        provider:
          keycloak:
            # https://www.keycloak.org/docs/latest/securing_apps/index.html#endpoints-2
            issuer-uri: http://localhost:50010/auth/realms/example
            # https://www.keycloak.org/docs/11.0/securing_apps/index.html
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: test-for-java

      resourceserver:
        jwt:
          issuer-uri: http://localhost:50010/auth/realms/example

  thymeleaf:
    prefix: file:slides/
    template-resolver-order: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

graphql:
  url: /api/v1
  tools:
    schema-location-pattern: graphql/*.schema.graphql

voyager:
  enabled: true
  endpoint: /api/v1
  cdn:
    enabled: false

logging:
  level:
    org:
#      neo4j:
#        ogm:
#          drivers:
#            bolt:
#              request:
#                BoltRequest: DEBUG
#
#            embedded:
#              request:
#                EmbeddedRequest: DEBUG

      springframework:
        data:
          neo4j: DEBUG
        security: DEBUG