#debug: true

app:
  slide:
    root-path: file:slides/

spring:
  application:
    name: magic-lantern-server
  cloud:
    gateway:
      routes:
        - uri: http://localhost:4200
          order: 10000
          predicates:
            - Path=/**
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/magic-lantern
    username: admin
    password: password123

  devtools:
    restart:
      exclude: META-INF/maven/**,META-INF/resources/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties

  codec:
    max-in-memory-size: 10MB
  security:
    oauth2:
      client:
        provider:
          keycloak:
            # https://www.keycloak.org/docs/latest/securing_apps/index.html#endpoints-2
            issuer-uri: http://localhost:50010/auth/realms/example
            # https://www.keycloak.org/docs/11.0/securing_apps/index.html
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: test-for-java
            client-name: Test for Java
            scope: openid

      resourceserver:
        jwt:
          issuer-uri: http://localhost:50010/auth/realms/example

  thymeleaf:
    cache: false
    prefix: file:slides/
    template-resolver-order: 1

  webflux:
    static-path-pattern: /public/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

graphql:
  url: /api/v1
  tools:
    schema-location-pattern: graphql/*.schema.graphql

voyager:
  enabled: true
  endpoint: /api/v1
  cdn:
    enabled: false

logging:
  level:
    root: info
