/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IAccountGroupAuthority
import io.github.novemdecillion.domain.Role

import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class AccountGroupAuthorityEntity(
    override var accountId: UUID? = null, 
    override var groupTransitionId: UUID? = null, 
    override var role: Role? = null
): IAccountGroupAuthority {


    override fun toString(): String {
        val sb = StringBuilder("AccountGroupAuthorityEntity (")

        sb.append(accountId)
        sb.append(", ").append(groupTransitionId)
        sb.append(", ").append(role)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IAccountGroupAuthority) {
        accountId = from.accountId
        groupTransitionId = from.groupTransitionId
        role = from.role
    }

    override fun <E : IAccountGroupAuthority> into(into: E): E {
        into.from(this)
        return into
    }
}
