/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IAccountGroupAuthority_1

import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class AccountGroupAuthority_1Entity(
    override var accountId: UUID? = null, 
    override var groupTransitionId: UUID? = null, 
    override var groupGenerationId: Int? = null, 
    override var role: JSONB? = null
): IAccountGroupAuthority_1 {


    override fun toString(): String {
        val sb = StringBuilder("AccountGroupAuthority_1Entity (")

        sb.append(accountId)
        sb.append(", ").append(groupTransitionId)
        sb.append(", ").append(groupGenerationId)
        sb.append(", ").append(role)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IAccountGroupAuthority_1) {
        accountId = from.accountId
        groupTransitionId = from.groupTransitionId
        groupGenerationId = from.groupGenerationId
        role = from.role
    }

    override fun <E : IAccountGroupAuthority_1> into(into: E): E {
        into.from(this)
        return into
    }
}
