/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.ICurrentGroupTransition

import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CurrentGroupTransitionEntity(
    override var groupTransitionId: UUID? = null, 
    override var groupGenerationId: UUID? = null, 
    override var groupOriginId: UUID? = null, 
    override var groupName: String? = null
): ICurrentGroupTransition {


    override fun toString(): String {
        val sb = StringBuilder("CurrentGroupTransitionEntity (")

        sb.append(groupTransitionId)
        sb.append(", ").append(groupGenerationId)
        sb.append(", ").append(groupOriginId)
        sb.append(", ").append(groupName)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ICurrentGroupTransition) {
        groupTransitionId = from.groupTransitionId
        groupGenerationId = from.groupGenerationId
        groupOriginId = from.groupOriginId
        groupName = from.groupName
    }

    override fun <E : ICurrentGroupTransition> into(into: E): E {
        into.from(this)
        return into
    }
}
