/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IGroupGenerationPeriod

import java.time.OffsetDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class GroupGenerationPeriodEntity(
    override var groupGenerationId: UUID? = null, 
    override var startDate: OffsetDateTime? = null, 
    override var endDate: OffsetDateTime? = null
): IGroupGenerationPeriod {


    override fun toString(): String {
        val sb = StringBuilder("GroupGenerationPeriodEntity (")

        sb.append(groupGenerationId)
        sb.append(", ").append(startDate)
        sb.append(", ").append(endDate)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IGroupGenerationPeriod) {
        groupGenerationId = from.groupGenerationId
        startDate = from.startDate
        endDate = from.endDate
    }

    override fun <E : IGroupGenerationPeriod> into(into: E): E {
        into.from(this)
        return into
    }
}
