/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IGroupGeneration

import java.time.LocalDate
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class GroupGenerationEntity(
    override var groupGenerationId: UUID? = null, 
    override var startDate: LocalDate? = null
): IGroupGeneration {


    override fun toString(): String {
        val sb = StringBuilder("GroupGenerationEntity (")

        sb.append(groupGenerationId)
        sb.append(", ").append(startDate)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IGroupGeneration) {
        groupGenerationId = from.groupGenerationId
        startDate = from.startDate
    }

    override fun <E : IGroupGeneration> into(into: E): E {
        into.from(this)
        return into
    }
}
