/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IGroupOrigin

import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class GroupOriginEntity(
    override var groupOriginId: UUID? = null
): IGroupOrigin {


    override fun toString(): String {
        val sb = StringBuilder("GroupOriginEntity (")

        sb.append(groupOriginId)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IGroupOrigin) {
        groupOriginId = from.groupOriginId
    }

    override fun <E : IGroupOrigin> into(into: E): E {
        into.from(this)
        return into
    }
}
