/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IGroup_1

import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Group_1Entity(
    override var groupTransitionId: UUID? = null, 
    override var groupGenerationId: Int? = null, 
    override var groupName: String? = null, 
    override var parentGroupTransitionId: UUID? = null
): IGroup_1 {


    override fun toString(): String {
        val sb = StringBuilder("Group_1Entity (")

        sb.append(groupTransitionId)
        sb.append(", ").append(groupGenerationId)
        sb.append(", ").append(groupName)
        sb.append(", ").append(parentGroupTransitionId)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IGroup_1) {
        groupTransitionId = from.groupTransitionId
        groupGenerationId = from.groupGenerationId
        groupName = from.groupName
        parentGroupTransitionId = from.parentGroupTransitionId
    }

    override fun <E : IGroup_1> into(into: E): E {
        into.from(this)
        return into
    }
}
