/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.ILesson

import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class LessonEntity(
    override var lessonId: UUID? = null, 
    override var groupOriginId: UUID? = null, 
    override var slideId: String? = null
): ILesson {


    override fun toString(): String {
        val sb = StringBuilder("LessonEntity (")

        sb.append(lessonId)
        sb.append(", ").append(groupOriginId)
        sb.append(", ").append(slideId)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ILesson) {
        lessonId = from.lessonId
        groupOriginId = from.groupOriginId
        slideId = from.slideId
    }

    override fun <E : ILesson> into(into: E): E {
        into.from(this)
        return into
    }
}
