/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.INotice

import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class NoticeEntity(
    override var noticeId: UUID? = null, 
    override var message: String? = null, 
    override var startAt: LocalDate? = null, 
    override var endAt: LocalDate? = null, 
    override var updateAt: OffsetDateTime? = null
): INotice {


    override fun toString(): String {
        val sb = StringBuilder("NoticeEntity (")

        sb.append(noticeId)
        sb.append(", ").append(message)
        sb.append(", ").append(startAt)
        sb.append(", ").append(endAt)
        sb.append(", ").append(updateAt)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: INotice) {
        noticeId = from.noticeId
        message = from.message
        startAt = from.startAt
        endAt = from.endAt
        updateAt = from.updateAt
    }

    override fun <E : INotice> into(into: E): E {
        into.from(this)
        return into
    }
}
