/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IRealm

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class RealmEntity(
    override var realmId: String? = null, 
    override var realmName: String? = null, 
    override var enabled: Boolean? = null, 
    override var syncAt: LocalDateTime? = null
): IRealm {


    override fun toString(): String {
        val sb = StringBuilder("RealmEntity (")

        sb.append(realmId)
        sb.append(", ").append(realmName)
        sb.append(", ").append(enabled)
        sb.append(", ").append(syncAt)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IRealm) {
        realmId = from.realmId
        realmName = from.realmName
        enabled = from.enabled
        syncAt = from.syncAt
    }

    override fun <E : IRealm> into(into: E): E {
        into.from(this)
        return into
    }
}
