/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.ISlide


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SlideEntity(
    override var slideId: String? = null
): ISlide {


    override fun toString(): String {
        val sb = StringBuilder("SlideEntity (")

        sb.append(slideId)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ISlide) {
        slideId = from.slideId
    }

    override fun <E : ISlide> into(into: E): E {
        into.from(this)
        return into
    }
}
