/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IStudy

import java.time.OffsetDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class StudyEntity(
    override var studyId: UUID? = null, 
    override var accountId: UUID? = null, 
    override var slideId: String? = null, 
    override var progress: String? = null, 
    override var progressRate: Int? = null, 
    override var answer: String? = null, 
    override var score: Int? = null, 
    override var startAt: OffsetDateTime? = null, 
    override var endAt: OffsetDateTime? = null
): IStudy {


    override fun toString(): String {
        val sb = StringBuilder("StudyEntity (")

        sb.append(studyId)
        sb.append(", ").append(accountId)
        sb.append(", ").append(slideId)
        sb.append(", ").append(progress)
        sb.append(", ").append(progressRate)
        sb.append(", ").append(answer)
        sb.append(", ").append(score)
        sb.append(", ").append(startAt)
        sb.append(", ").append(endAt)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IStudy) {
        studyId = from.studyId
        accountId = from.accountId
        slideId = from.slideId
        progress = from.progress
        progressRate = from.progressRate
        answer = from.answer
        score = from.score
        startAt = from.startAt
        endAt = from.endAt
    }

    override fun <E : IStudy> into(into: E): E {
        into.from(this)
        return into
    }
}
