/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.daos


import io.github.novemdecillion.adapter.jooq.tables.AccountGroupAuthority_1Table
import io.github.novemdecillion.adapter.jooq.tables.pojos.AccountGroupAuthority_1Entity
import io.github.novemdecillion.adapter.jooq.tables.records.AccountGroupAuthority_1Record

import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.JSONB
import org.jooq.Record3
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountGroupAuthority_1Dao(configuration: Configuration?) : DAOImpl<AccountGroupAuthority_1Record, AccountGroupAuthority_1Entity, Record3<UUID?, UUID?, Int?>>(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1, AccountGroupAuthority_1Entity::class.java, configuration) {

    /**
     * Create a new AccountGroupAuthority_1Dao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: AccountGroupAuthority_1Entity): Record3<UUID?, UUID?, Int?>? = compositeKeyRecord(o.accountId, o.groupTransitionId, o.groupGenerationId)

    /**
     * Fetch records that have <code>account_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfAccountIdTable(lowerInclusive: UUID?, upperInclusive: UUID?): List<AccountGroupAuthority_1Entity> = fetchRange(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.ACCOUNT_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>account_id IN (values)</code>
     */
    fun fetchByAccountIdTable(vararg values: UUID): List<AccountGroupAuthority_1Entity> = fetch(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.ACCOUNT_ID, *values)

    /**
     * Fetch records that have <code>group_transition_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfGroupTransitionIdTable(lowerInclusive: UUID?, upperInclusive: UUID?): List<AccountGroupAuthority_1Entity> = fetchRange(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.GROUP_TRANSITION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>group_transition_id IN (values)</code>
     */
    fun fetchByGroupTransitionIdTable(vararg values: UUID): List<AccountGroupAuthority_1Entity> = fetch(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.GROUP_TRANSITION_ID, *values)

    /**
     * Fetch records that have <code>group_generation_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfGroupGenerationIdTable(lowerInclusive: Int?, upperInclusive: Int?): List<AccountGroupAuthority_1Entity> = fetchRange(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.GROUP_GENERATION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>group_generation_id IN (values)</code>
     */
    fun fetchByGroupGenerationIdTable(vararg values: Int): List<AccountGroupAuthority_1Entity> = fetch(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.GROUP_GENERATION_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfRoleTable(lowerInclusive: JSONB?, upperInclusive: JSONB?): List<AccountGroupAuthority_1Entity> = fetchRange(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.ROLE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    fun fetchByRoleTable(vararg values: JSONB): List<AccountGroupAuthority_1Entity> = fetch(AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1.ROLE, *values)
}
