/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.daos


import io.github.novemdecillion.adapter.jooq.tables.GroupGenerationTable
import io.github.novemdecillion.adapter.jooq.tables.pojos.GroupGenerationEntity
import io.github.novemdecillion.adapter.jooq.tables.records.GroupGenerationRecord

import java.time.LocalDate
import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GroupGenerationDao(configuration: Configuration?) : DAOImpl<GroupGenerationRecord, GroupGenerationEntity, UUID>(GroupGenerationTable.GROUP_GENERATION, GroupGenerationEntity::class.java, configuration) {

    /**
     * Create a new GroupGenerationDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: GroupGenerationEntity): UUID? = o.groupGenerationId

    /**
     * Fetch records that have <code>group_generation_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfGroupGenerationIdTable(lowerInclusive: UUID?, upperInclusive: UUID?): List<GroupGenerationEntity> = fetchRange(GroupGenerationTable.GROUP_GENERATION.GROUP_GENERATION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>group_generation_id IN (values)</code>
     */
    fun fetchByGroupGenerationIdTable(vararg values: UUID): List<GroupGenerationEntity> = fetch(GroupGenerationTable.GROUP_GENERATION.GROUP_GENERATION_ID, *values)

    /**
     * Fetch a unique record that has <code>group_generation_id = value</code>
     */
    fun fetchOneByGroupGenerationIdTable(value: UUID): GroupGenerationEntity? = fetchOne(GroupGenerationTable.GROUP_GENERATION.GROUP_GENERATION_ID, value)

    /**
     * Fetch records that have <code>start_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfStartDateTable(lowerInclusive: LocalDate?, upperInclusive: LocalDate?): List<GroupGenerationEntity> = fetchRange(GroupGenerationTable.GROUP_GENERATION.START_DATE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>start_date IN (values)</code>
     */
    fun fetchByStartDateTable(vararg values: LocalDate): List<GroupGenerationEntity> = fetch(GroupGenerationTable.GROUP_GENERATION.START_DATE, *values)
}
