/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.daos


import io.github.novemdecillion.adapter.jooq.tables.GroupTransitionTable
import io.github.novemdecillion.adapter.jooq.tables.pojos.GroupTransitionEntity
import io.github.novemdecillion.adapter.jooq.tables.records.GroupTransitionRecord

import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.Record2
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GroupTransitionDao(configuration: Configuration?) : DAOImpl<GroupTransitionRecord, GroupTransitionEntity, Record2<UUID?, Int?>>(GroupTransitionTable.GROUP_TRANSITION, GroupTransitionEntity::class.java, configuration) {

    /**
     * Create a new GroupTransitionDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: GroupTransitionEntity): Record2<UUID?, Int?>? = compositeKeyRecord(o.groupTransitionId, o.groupGenerationId)

    /**
     * Fetch records that have <code>group_transition_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfGroupTransitionIdTable(lowerInclusive: UUID?, upperInclusive: UUID?): List<GroupTransitionEntity> = fetchRange(GroupTransitionTable.GROUP_TRANSITION.GROUP_TRANSITION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>group_transition_id IN (values)</code>
     */
    fun fetchByGroupTransitionIdTable(vararg values: UUID): List<GroupTransitionEntity> = fetch(GroupTransitionTable.GROUP_TRANSITION.GROUP_TRANSITION_ID, *values)

    /**
     * Fetch records that have <code>group_generation_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfGroupGenerationIdTable(lowerInclusive: Int?, upperInclusive: Int?): List<GroupTransitionEntity> = fetchRange(GroupTransitionTable.GROUP_TRANSITION.GROUP_GENERATION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>group_generation_id IN (values)</code>
     */
    fun fetchByGroupGenerationIdTable(vararg values: Int): List<GroupTransitionEntity> = fetch(GroupTransitionTable.GROUP_TRANSITION.GROUP_GENERATION_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>group_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfGroupNameTable(lowerInclusive: String?, upperInclusive: String?): List<GroupTransitionEntity> = fetchRange(GroupTransitionTable.GROUP_TRANSITION.GROUP_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>group_name IN (values)</code>
     */
    fun fetchByGroupNameTable(vararg values: String): List<GroupTransitionEntity> = fetch(GroupTransitionTable.GROUP_TRANSITION.GROUP_NAME, *values)

    /**
     * Fetch records that have <code>parent_group_transition_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfParentGroupTransitionIdTable(lowerInclusive: UUID?, upperInclusive: UUID?): List<GroupTransitionEntity> = fetchRange(GroupTransitionTable.GROUP_TRANSITION.PARENT_GROUP_TRANSITION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>parent_group_transition_id IN (values)</code>
     */
    fun fetchByParentGroupTransitionIdTable(vararg values: UUID): List<GroupTransitionEntity> = fetch(GroupTransitionTable.GROUP_TRANSITION.PARENT_GROUP_TRANSITION_ID, *values)
}
