/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.references


import io.github.novemdecillion.adapter.jooq.tables.AccountGroupAuthorityTable
import io.github.novemdecillion.adapter.jooq.tables.AccountGroupAuthority_0Table
import io.github.novemdecillion.adapter.jooq.tables.AccountGroupAuthority_1Table
import io.github.novemdecillion.adapter.jooq.tables.AccountTable
import io.github.novemdecillion.adapter.jooq.tables.CurrentAccountGroupAuthorityTable
import io.github.novemdecillion.adapter.jooq.tables.CurrentGroupTransitionTable
import io.github.novemdecillion.adapter.jooq.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.adapter.jooq.tables.GroupGenerationTable
import io.github.novemdecillion.adapter.jooq.tables.GroupTransitionTable
import io.github.novemdecillion.adapter.jooq.tables.Group_0Table
import io.github.novemdecillion.adapter.jooq.tables.Group_1Table
import io.github.novemdecillion.adapter.jooq.tables.LessonTable
import io.github.novemdecillion.adapter.jooq.tables.NoticeTable
import io.github.novemdecillion.adapter.jooq.tables.RealmTable
import io.github.novemdecillion.adapter.jooq.tables.StudyTable
import io.github.novemdecillion.adapter.jooq.tables.UserAggregateTable



/**
 * The table <code>account</code>.
 */
val ACCOUNT = AccountTable.ACCOUNT

/**
 * The table <code>account_group_authority</code>.
 */
val ACCOUNT_GROUP_AUTHORITY = AccountGroupAuthorityTable.ACCOUNT_GROUP_AUTHORITY

/**
 * The table <code>account_group_authority_0</code>.
 */
val ACCOUNT_GROUP_AUTHORITY_0 = AccountGroupAuthority_0Table.ACCOUNT_GROUP_AUTHORITY_0

/**
 * The table <code>account_group_authority_1</code>.
 */
val ACCOUNT_GROUP_AUTHORITY_1 = AccountGroupAuthority_1Table.ACCOUNT_GROUP_AUTHORITY_1

/**
 * The table <code>current_account_group_authority</code>.
 */
val CURRENT_ACCOUNT_GROUP_AUTHORITY = CurrentAccountGroupAuthorityTable.CURRENT_ACCOUNT_GROUP_AUTHORITY

/**
 * The table <code>current_group_transition</code>.
 */
val CURRENT_GROUP_TRANSITION = CurrentGroupTransitionTable.CURRENT_GROUP_TRANSITION

/**
 * The table <code>flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>group_0</code>.
 */
val GROUP_0 = Group_0Table.GROUP_0

/**
 * The table <code>group_1</code>.
 */
val GROUP_1 = Group_1Table.GROUP_1

/**
 * The table <code>group_generation</code>.
 */
val GROUP_GENERATION = GroupGenerationTable.GROUP_GENERATION

/**
 * The table <code>group_transition</code>.
 */
val GROUP_TRANSITION = GroupTransitionTable.GROUP_TRANSITION

/**
 * The table <code>lesson</code>.
 */
val LESSON = LessonTable.LESSON

/**
 * The table <code>notice</code>.
 */
val NOTICE = NoticeTable.NOTICE

/**
 * The table <code>realm</code>.
 */
val REALM = RealmTable.REALM

/**
 * The table <code>study</code>.
 */
val STUDY = StudyTable.STUDY

/**
 * The table <code>user_aggregate</code>.
 */
val USER_AGGREGATE = UserAggregateTable.USER_AGGREGATE
