/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IAccount : Serializable {
    var accountId: UUID?
    var accountName: String?
    var password: String?
    var userName: String?
    var givenName: String?
    var familyName: String?
    var eastern: Boolean?
    var email: String?
    var realm: String?
    var enabled: Boolean?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAccount
     */
    fun from(from: IAccount)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAccount
     */
    fun <E : IAccount> into(into: E): E
}
