/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ICurrentAccountGroupAuthority : Serializable {
    var accountId: UUID?
    var groupTransitionId: UUID?
    var groupGenerationId: Int?
    var role: JSONB?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICurrentAccountGroupAuthority
     */
    fun from(from: ICurrentAccountGroupAuthority)

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICurrentAccountGroupAuthority
     */
    fun <E : ICurrentAccountGroupAuthority> into(into: E): E
}
