/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.time.OffsetDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IGroupGeneration : Serializable {
    var groupGenerationId: UUID?
    var startDate: OffsetDateTime?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IGroupGeneration
     */
    fun from(from: IGroupGeneration)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IGroupGeneration
     */
    fun <E : IGroupGeneration> into(into: E): E
}
