/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IGroupOrigin : Serializable {
    var groupOriginId: UUID?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IGroupOrigin
     */
    fun from(from: IGroupOrigin)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IGroupOrigin
     */
    fun <E : IGroupOrigin> into(into: E): E
}
