/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface INotice : Serializable {
    var noticeId: UUID?
    var message: String?
    var startAt: LocalDate?
    var endAt: LocalDate?
    var updateAt: OffsetDateTime?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface INotice
     */
    fun from(from: INotice)

    /**
     * Copy data into another generated Record/POJO implementing the common interface INotice
     */
    fun <E : INotice> into(into: E): E
}
