/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IRealm : Serializable {
    var realmId: String?
    var realmName: String?
    var enabled: Boolean?
    var syncAt: LocalDateTime?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IRealm
     */
    fun from(from: IRealm)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IRealm
     */
    fun <E : IRealm> into(into: E): E
}
