/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ISlide : Serializable {
    var slideId: String?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISlide
     */
    fun from(from: ISlide)

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISlide
     */
    fun <E : ISlide> into(into: E): E
}
