/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.sequences


import io.github.novemdecillion.adapter.jooq.DefaultSchema

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>group_generation_id_seq</code>
 */
val GROUP_GENERATION_ID_SEQ: Sequence<Long> = Internal.createSequence("group_generation_id_seq", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT.nullable(false), 2, null, null, null, false, null)
